/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SupplierRole;

/**
 *
 * @author vikram
 */


import Business.Business;
import Business.Markets.MarketList;
import Business.Supplier.Supplier;
import java.awt.CardLayout;
import javax.swing.JPanel;


public class SupplierWorkAreaJPanel extends javax.swing.JPanel {
    
private JPanel userProcessContainer;
private Business business;
private Supplier supplier;
private MarketList marketList;
    /**
     * Creates new form SupplierWorkAreaJPanel
     */
    public SupplierWorkAreaJPanel(JPanel userProcessContainer, Supplier supplier, MarketList marketList) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.supplier = supplier;
        this.marketList = marketList;
        supplierNameJTextField.setText(supplier.getSupplierName());
        supplierIdJTextField.setText(String.valueOf(supplier.getSupplierId()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageProductButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        supplierIdJTextField = new javax.swing.JTextField();
        supplierNameJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Supplier Work Area");
        add(jLabel1);
        jLabel1.setBounds(10, 30, 780, 29);

        manageProductButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageProductButton.setText("Manage Product Catalog >>");
        manageProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProductButtonActionPerformed(evt);
            }
        });
        add(manageProductButton);
        manageProductButton.setBounds(440, 420, 257, 31);

        jLabel2.setText("Supplier Id:");
        add(jLabel2);
        jLabel2.setBounds(230, 210, 80, 30);

        supplierIdJTextField.setEnabled(false);
        supplierIdJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierIdJTextFieldActionPerformed(evt);
            }
        });
        add(supplierIdJTextField);
        supplierIdJTextField.setBounds(320, 210, 230, 30);

        supplierNameJTextField.setEnabled(false);
        add(supplierNameJTextField);
        supplierNameJTextField.setBounds(320, 160, 230, 30);

        jLabel4.setText("Supplier Name:");
        add(jLabel4);
        jLabel4.setBounds(230, 160, 80, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void manageProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProductButtonActionPerformed

        ManageProductCatalogJPanel mpcjp = new ManageProductCatalogJPanel(userProcessContainer, supplier, marketList);
        userProcessContainer.add("ManageProductCatalogJPanel", mpcjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageProductButtonActionPerformed

    private void supplierIdJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierIdJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierIdJTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton manageProductButton;
    private javax.swing.JTextField supplierIdJTextField;
    private javax.swing.JTextField supplierNameJTextField;
    // End of variables declaration//GEN-END:variables
}
