/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminRole;

import UserInterface.AdminRole.ManageSalesPerson.ManageSalesJPanel;
import UserInterface.AdminRole.ManageSuppliers.ManageSuppliersJPanel;
import Business.Business;
import Business.SalesPerson.SalesPersonDirectory;
import Business.Supplier.SupplierDirectory;
import UserInterface.AdminRole.ManageCustomers.ManageCustomersJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author vikram
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Business business;
    private SupplierDirectory supplierDirectory;
    private SalesPersonDirectory salesPersonDirectory;

    public AdminWorkAreaJPanel(JPanel userProcessContainer, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.supplierDirectory = business.getSupplierDirectory();
        this.salesPersonDirectory = business.getSalesPersonDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageSuppliers = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnManageCustomers = new javax.swing.JButton();
        btnManageSalesPerson = new javax.swing.JButton();
        btnManageSuppliers3 = new javax.swing.JButton();

        btnManageSuppliers.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnManageSuppliers.setText("Manage Suppliers >>");
        btnManageSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageSuppliersActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area -Administrative Role");

        btnManageCustomers.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnManageCustomers.setText("Manage Customers >>");
        btnManageCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCustomersActionPerformed(evt);
            }
        });

        btnManageSalesPerson.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnManageSalesPerson.setText("Manage Salespersons >>");
        btnManageSalesPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageSalesPersonActionPerformed(evt);
            }
        });

        btnManageSuppliers3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnManageSuppliers3.setText("View Statistics >>");
        btnManageSuppliers3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageSuppliers3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(186, 186, 186))
            .addGroup(layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManageSuppliers3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageSalesPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addComponent(btnManageSuppliers)
                .addGap(18, 18, 18)
                .addComponent(btnManageSalesPerson)
                .addGap(18, 18, 18)
                .addComponent(btnManageCustomers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManageSuppliers3)
                .addContainerGap(242, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSuppliersActionPerformed
        ManageSuppliersJPanel ms = new ManageSuppliersJPanel(userProcessContainer, supplierDirectory,business.getUserAccountDirectory());
        userProcessContainer.add("ManageSuppliersJPanel", ms);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageSuppliersActionPerformed

    private void btnManageCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCustomersActionPerformed
        // TODO add your handling code here:
        ManageCustomersJPanel msalesPerson = new ManageCustomersJPanel(userProcessContainer,business.getCustomerDirectory() ,business.getUserAccountDirectory(), business.getMarketList());
        userProcessContainer.add("ManageCustomersJPanel", msalesPerson);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageCustomersActionPerformed

    private void btnManageSalesPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSalesPersonActionPerformed
        ManageSalesJPanel msalesPerson = new ManageSalesJPanel(userProcessContainer, salesPersonDirectory, business.getUserAccountDirectory());
        
        userProcessContainer.add("ManageSalesJPanel", msalesPerson);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageSalesPersonActionPerformed

    private void btnManageSuppliers3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSuppliers3ActionPerformed

        ViewStatisticsJPanel viewStatistics = new ViewStatisticsJPanel(userProcessContainer, business);
        userProcessContainer.add("ViewStatisticsJPanel", viewStatistics);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnManageSuppliers3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageCustomers;
    private javax.swing.JButton btnManageSalesPerson;
    private javax.swing.JButton btnManageSuppliers;
    private javax.swing.JButton btnManageSuppliers3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
