/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Airplanes;
import Business.AirplanesCatalog;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author vikram
 */

public class CreateJPanel extends javax.swing.JPanel {
    /**
     * Creates new form CreateJPanel
     */
    //private Airplanes airplanes;
    AirplanesCatalog airplanesCatalog;
    
    public CreateJPanel(AirplanesCatalog airplanesCatalog) {
        initComponents();
         this.airplanesCatalog = airplanesCatalog;
         textPanel.setVisible(false);
         csvLoadPanel.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        modelNoTxt1 = new javax.swing.JTextField();
        manufacturedByTxt1 = new javax.swing.JTextField();
        serialNoTxt1 = new javax.swing.JTextField();
        yearTxt1 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        modelNoTxt2 = new javax.swing.JTextField();
        manufacturedByTxt2 = new javax.swing.JTextField();
        serialNoTxt2 = new javax.swing.JTextField();
        yearTxt2 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        modelNoTxt3 = new javax.swing.JTextField();
        manufacturedByTxt3 = new javax.swing.JTextField();
        serialNoTxt3 = new javax.swing.JTextField();
        yearTxt3 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jTextField12 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        textPanel = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        yearTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        numberOfSeatsTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        availableDateTxt = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        modelNoTxt = new javax.swing.JTextField();
        airportTxt = new javax.swing.JTextField();
        serialNoTxt = new javax.swing.JTextField();
        maintainceCertificateTxt = new javax.swing.JTextField();
        manufacturedByTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        selectionComboBox = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        csvLoadPanel = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jLabel1.setText("Add an Airplane");
        add(jLabel1);
        jLabel1.setBounds(280, 20, 220, 30);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Add an Airplane");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, 50, 190, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Maintainence Certificate");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 400, 130, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Year of Manufacture");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(54, 300, 120, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Manufactured By");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(80, 250, 100, 15);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Model Number");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(84, 200, 90, 15);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Serial Number");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(88, 150, 90, 15);

        modelNoTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelNoTxt1ActionPerformed(evt);
            }
        });
        jPanel1.add(modelNoTxt1);
        modelNoTxt1.setBounds(180, 190, 270, 30);
        jPanel1.add(manufacturedByTxt1);
        manufacturedByTxt1.setBounds(180, 240, 270, 30);
        jPanel1.add(serialNoTxt1);
        serialNoTxt1.setBounds(180, 140, 270, 30);
        jPanel1.add(yearTxt1);
        yearTxt1.setBounds(180, 290, 270, 30);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(180, 390, 270, 30);

        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(270, 480, 73, 23);
        jPanel1.add(jTextField8);
        jTextField8.setBounds(180, 340, 270, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("No of seats");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(60, 350, 100, 15);

        jPanel2.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("Add an Airplane");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(230, 50, 190, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Maintainence Certificate");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(30, 400, 130, 15);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Year of Manufacture");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(54, 300, 120, 15);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Manufactured By");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(80, 250, 100, 15);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Model Number");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(84, 200, 90, 15);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Serial Number");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(88, 150, 90, 15);

        modelNoTxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelNoTxt2ActionPerformed(evt);
            }
        });
        jPanel2.add(modelNoTxt2);
        modelNoTxt2.setBounds(180, 190, 270, 30);
        jPanel2.add(manufacturedByTxt2);
        manufacturedByTxt2.setBounds(180, 240, 270, 30);
        jPanel2.add(serialNoTxt2);
        serialNoTxt2.setBounds(180, 140, 270, 30);
        jPanel2.add(yearTxt2);
        yearTxt2.setBounds(180, 290, 270, 30);
        jPanel2.add(jTextField9);
        jTextField9.setBounds(180, 390, 270, 30);

        jButton3.setText("ADD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(270, 480, 73, 23);
        jPanel2.add(jTextField10);
        jTextField10.setBounds(180, 340, 270, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("No of seats");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(60, 350, 100, 15);

        jPanel3.setLayout(null);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel22.setText("Add an Airplane");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(230, 50, 190, 30);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Maintainence Certificate");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(30, 400, 130, 15);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Year of Manufacture");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(54, 300, 120, 15);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("Manufactured By");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(80, 250, 100, 15);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("Model Number");
        jPanel3.add(jLabel26);
        jLabel26.setBounds(84, 200, 90, 15);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("Serial Number");
        jPanel3.add(jLabel27);
        jLabel27.setBounds(88, 150, 90, 15);

        modelNoTxt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelNoTxt3ActionPerformed(evt);
            }
        });
        jPanel3.add(modelNoTxt3);
        modelNoTxt3.setBounds(180, 190, 270, 30);
        jPanel3.add(manufacturedByTxt3);
        manufacturedByTxt3.setBounds(180, 240, 270, 30);
        jPanel3.add(serialNoTxt3);
        serialNoTxt3.setBounds(180, 140, 270, 30);
        jPanel3.add(yearTxt3);
        yearTxt3.setBounds(180, 290, 270, 30);
        jPanel3.add(jTextField11);
        jTextField11.setBounds(180, 390, 270, 30);

        jButton4.setText("ADD");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(270, 480, 73, 23);
        jPanel3.add(jTextField12);
        jTextField12.setBounds(180, 340, 270, 30);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("No of seats");
        jPanel3.add(jLabel28);
        jLabel28.setBounds(60, 350, 100, 15);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 0, 0, 0);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 0, 0);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 0, 0);

        textPanel.setLayout(null);

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setText("Maintainence Certificate");
        textPanel.add(jLabel29);
        jLabel29.setBounds(40, 280, 130, 15);

        yearTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearTxtActionPerformed(evt);
            }
        });
        yearTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                yearTxtKeyTyped(evt);
            }
        });
        textPanel.add(yearTxt);
        yearTxt.setBounds(190, 170, 270, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Model Number");
        textPanel.add(jLabel6);
        jLabel6.setBounds(90, 80, 90, 15);

        numberOfSeatsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfSeatsTxtActionPerformed(evt);
            }
        });
        numberOfSeatsTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numberOfSeatsTxtKeyTyped(evt);
            }
        });
        textPanel.add(numberOfSeatsTxt);
        numberOfSeatsTxt.setBounds(190, 220, 270, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Serial Number");
        textPanel.add(jLabel7);
        jLabel7.setBounds(100, 30, 90, 15);

        availableDateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availableDateTxtActionPerformed(evt);
            }
        });
        textPanel.add(availableDateTxt);
        availableDateTxt.setBounds(190, 360, 270, 30);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("Airport");
        textPanel.add(jLabel30);
        jLabel30.setBounds(120, 320, 70, 15);
        textPanel.add(modelNoTxt);
        modelNoTxt.setBounds(190, 70, 270, 30);
        textPanel.add(airportTxt);
        airportTxt.setBounds(190, 310, 270, 30);
        textPanel.add(serialNoTxt);
        serialNoTxt.setBounds(190, 20, 270, 30);

        maintainceCertificateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintainceCertificateTxtActionPerformed(evt);
            }
        });
        textPanel.add(maintainceCertificateTxt);
        maintainceCertificateTxt.setBounds(190, 270, 270, 30);
        textPanel.add(manufacturedByTxt);
        manufacturedByTxt.setBounds(190, 120, 270, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Manufactured By");
        textPanel.add(jLabel5);
        jLabel5.setBounds(90, 130, 100, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Departure Date");
        textPanel.add(jLabel3);
        jLabel3.setBounds(80, 370, 100, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Year of Manufacture");
        textPanel.add(jLabel4);
        jLabel4.setBounds(60, 180, 120, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("No of seats");
        textPanel.add(jLabel8);
        jLabel8.setBounds(100, 230, 80, 15);

        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        textPanel.add(addBtn);
        addBtn.setBounds(260, 410, 60, 30);

        add(textPanel);
        textPanel.setBounds(110, 230, 520, 450);

        selectionComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        selectionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Add Items Manually", "Load a CSV File" }));
        selectionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectionComboBoxActionPerformed(evt);
            }
        });
        add(selectionComboBox);
        selectionComboBox.setBounds(280, 90, 350, 30);

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel31.setText("Select an option to choose to add an Airplane ");
        add(jLabel31);
        jLabel31.setBounds(20, 90, 260, 30);

        csvLoadPanel.setLayout(null);

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("CSV File Added Successfully");
        csvLoadPanel.add(jLabel32);
        jLabel32.setBounds(100, 40, 200, 30);

        add(csvLoadPanel);
        csvLoadPanel.setBounds(140, 130, 410, 90);
    }// </editor-fold>//GEN-END:initComponents

    private void modelNoTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelNoTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelNoTxt1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void modelNoTxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelNoTxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelNoTxt2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void modelNoTxt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelNoTxt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelNoTxt3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void selectionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectionComboBoxActionPerformed
        // TODO add your handling code here:
        textPanel.setVisible(false);
        csvLoadPanel.setVisible(false);
        if (selectionComboBox.getSelectedItem().toString() == "Add Items Manually") {
            textPanel.setVisible(true);
        }
        if(selectionComboBox.getSelectedItem().toString() == "Load a CSV File"){
            csvLoadPanel.setVisible(true);
            BufferedReader br = null;
        try
        {
            //Reading the csv file
            br = new BufferedReader(new FileReader("newdata.csv"));
            //Create List for holding Employee objects
            String line = "";
            //Read to skip the header
            //br.readLine();
            Airplanes air = new Airplanes();
            //Reading from the second line
            while ((line = br.readLine()) != null) 
            {
                String[] airplaneDetails = line.split(",");
                Date availDate;
                
                if(airplaneDetails.length > 0 )
                {
                    Airplanes airplaneCat = airplanesCatalog.addAirplanes();
                    airplaneCat.setSerialNo(airplaneDetails[0]);
                    airplaneCat.setModelNo(airplaneDetails[1]);
                    airplaneCat.setManufacturer(airplaneDetails[2]);
                    airplaneCat.setYearOfManufacture(Integer.parseInt(airplaneDetails[3]));
                    airplaneCat.setNumberOfSeats(Integer.parseInt(airplaneDetails[4]));
                    airplaneCat.setMaintaineneceCertificate(airplaneDetails[5]);
                    airplaneCat.setAirport(airplaneDetails[6]);
                    SimpleDateFormat date = new SimpleDateFormat("dd-mm-yyyy");
                    airplaneCat.setDepartureDate(date.parse(airplaneDetails[7]));
                    airplaneCat.setCatalogUpdatedDate(date.parse(airplaneDetails[8]));
                }
            }
        }
        catch(Exception ee)
        {
            ee.printStackTrace();
        }
        finally
        {
            try
            {
                br.close();
            }
            catch(IOException ie)
            {
                System.out.println("Error occured while closing the BufferedReader");
                ie.printStackTrace();
            }
        }
    }    
    }//GEN-LAST:event_selectionComboBoxActionPerformed

    private void maintainceCertificateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintainceCertificateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maintainceCertificateTxtActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        Date date = new Date();
        Date availableDate = null;
        String serialNo = serialNoTxt.getText();
        String modelNo = modelNoTxt.getText();
        String manufacturer = manufacturedByTxt.getText();
        int year = Integer.parseInt(yearTxt.getText());
        int seats = Integer.parseInt(numberOfSeatsTxt.getText());
        String maintainence = maintainceCertificateTxt.getText();
        String airport = airportTxt.getText();
        //String timeStamp = new SimpleDateFormat("yyyy.MM.dd.HH.mm.ss").format(new java.util.Date());
        try {
            availableDate = new SimpleDateFormat("dd/MM/yyyy").parse(availableDateTxt.getText());
        } catch (ParseException ex) {
            Logger.getLogger(CreateJPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Enter the date in proper format");
            return;
        }
        Date catalogueUpdate = new Date();
        Airplanes air = airplanesCatalog.addAirplanes();
        air.setSerialNo(serialNo);
        air.setModelNo(modelNo);
        air.setManufacturer(manufacturer);
        air.setYearOfManufacture(year);
        air.setNumberOfSeats(seats);
        air.setMaintaineneceCertificate(maintainence);
        air.setAirport(airport);
        air.setDepartureDate(availableDate);
        air.setCatalogUpdatedDate(catalogueUpdate);
        
        JOptionPane.showMessageDialog(null, "Airplanes added Successfully");
    }//GEN-LAST:event_addBtnActionPerformed

    private void availableDateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availableDateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availableDateTxtActionPerformed

    private void yearTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearTxtKeyTyped
        // TODO add your handling code here:
        char year= evt.getKeyChar();
        if (!(Character.isDigit(year) || (year==KeyEvent.VK_BACK_SPACE) || (year==KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_yearTxtKeyTyped

    private void numberOfSeatsTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numberOfSeatsTxtKeyTyped
        // TODO add your handling code here:
        char seats = evt.getKeyChar();
        if (!(Character.isDigit(seats) || (seats==KeyEvent.VK_BACK_SPACE) || (seats==KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_numberOfSeatsTxtKeyTyped

    private void yearTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearTxtActionPerformed

    private void numberOfSeatsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfSeatsTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOfSeatsTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField airportTxt;
    private javax.swing.JTextField availableDateTxt;
    private javax.swing.JPanel csvLoadPanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField maintainceCertificateTxt;
    private javax.swing.JTextField manufacturedByTxt;
    private javax.swing.JTextField manufacturedByTxt1;
    private javax.swing.JTextField manufacturedByTxt2;
    private javax.swing.JTextField manufacturedByTxt3;
    private javax.swing.JTextField modelNoTxt;
    private javax.swing.JTextField modelNoTxt1;
    private javax.swing.JTextField modelNoTxt2;
    private javax.swing.JTextField modelNoTxt3;
    private javax.swing.JTextField numberOfSeatsTxt;
    private javax.swing.JComboBox<String> selectionComboBox;
    private javax.swing.JTextField serialNoTxt;
    private javax.swing.JTextField serialNoTxt1;
    private javax.swing.JTextField serialNoTxt2;
    private javax.swing.JTextField serialNoTxt3;
    private javax.swing.JPanel textPanel;
    private javax.swing.JTextField yearTxt;
    private javax.swing.JTextField yearTxt1;
    private javax.swing.JTextField yearTxt2;
    private javax.swing.JTextField yearTxt3;
    // End of variables declaration//GEN-END:variables
}
