/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Airplanes;
import Business.AirplanesCatalog;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vikram
 */
public class SearchJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchJPanel
     */
    private AirplanesCatalog airplanesCatalog;

    public SearchJPanel() {
        
    }
    
    public SearchJPanel(AirplanesCatalog airplanesCatalog) {
        initComponents();
        this.airplanesCatalog = airplanesCatalog;
        textPanel.setVisible(false);
        populateTable();
    }
    
    
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)airlinesTable.getModel();
        dtm.setRowCount(0);
        SimpleDateFormat date = new SimpleDateFormat("dd-mm-yyyy");
        
        for(Airplanes as: airplanesCatalog.getAirplanesCatalog()){
            Object row[]= new Object[8]; 
            row[0]=as;
            row[1] = as.getModelNo();
            row[2] = as.getManufacturer();
            row[3] = as.getYearOfManufacture();
            row[4] = as.getNumberOfSeats();
            row[5] = as.getMaintaineneceCertificate();
            row[6] = as.getAirport();
            String availDate = date.format(as.getDepartureDate());
            row[7] = availDate;
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jLabel1 = new javax.swing.JLabel();
        viewJBtn = new javax.swing.JButton();
        deleteJBtn = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        airlinesTable = new javax.swing.JTable();
        textPanel = new javax.swing.JPanel();
        updateBtn = new javax.swing.JButton();
        yearTxt = new javax.swing.JTextField();
        manufacturedByTxt = new javax.swing.JTextField();
        serialNoTxt = new javax.swing.JTextField();
        modelNoTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        numberOfSeatsTxt = new javax.swing.JTextField();
        maintainceCertificateTxt = new javax.swing.JTextField();
        airportTxt = new javax.swing.JTextField();
        availableDateTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setAutoscrolls(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jLabel1.setText("View Airline Details");
        add(jLabel1);
        jLabel1.setBounds(550, 50, 260, 40);

        viewJBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        viewJBtn.setText("View");
        viewJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewJBtnActionPerformed(evt);
            }
        });
        add(viewJBtn);
        viewJBtn.setBounds(440, 360, 80, 30);

        deleteJBtn.setText("Delete");
        deleteJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteJBtnActionPerformed(evt);
            }
        });
        add(deleteJBtn);
        deleteJBtn.setBounds(690, 360, 80, 30);

        airlinesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial No", "Model No", "Manufactured By", "Year of Manufacture", "No. of seats", "Maintainence Certificate", "Airport", "Departure Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane11.setViewportView(airlinesTable);

        add(jScrollPane11);
        jScrollPane11.setBounds(50, 110, 1210, 210);

        textPanel.setLayout(null);

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        textPanel.add(updateBtn);
        updateBtn.setBounds(480, 210, 80, 30);

        yearTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                yearTxtKeyTyped(evt);
            }
        });
        textPanel.add(yearTxt);
        yearTxt.setBounds(190, 130, 270, 30);
        textPanel.add(manufacturedByTxt);
        manufacturedByTxt.setBounds(190, 90, 270, 30);
        textPanel.add(serialNoTxt);
        serialNoTxt.setBounds(190, 10, 270, 30);
        textPanel.add(modelNoTxt);
        modelNoTxt.setBounds(190, 50, 270, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Serial Number");
        textPanel.add(jLabel7);
        jLabel7.setBounds(100, 10, 90, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Model Number");
        textPanel.add(jLabel6);
        jLabel6.setBounds(90, 60, 90, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Manufactured By");
        textPanel.add(jLabel5);
        jLabel5.setBounds(80, 100, 100, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Year of Manufacture");
        textPanel.add(jLabel4);
        jLabel4.setBounds(70, 140, 120, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Available Date");
        textPanel.add(jLabel3);
        jLabel3.setBounds(590, 140, 90, 20);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("Airport");
        textPanel.add(jLabel30);
        jLabel30.setBounds(600, 100, 70, 20);

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setText("Maintainence Certificate");
        textPanel.add(jLabel29);
        jLabel29.setBounds(540, 60, 130, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("No of seats");
        textPanel.add(jLabel8);
        jLabel8.setBounds(590, 20, 80, 20);
        textPanel.add(numberOfSeatsTxt);
        numberOfSeatsTxt.setBounds(680, 10, 270, 30);
        textPanel.add(maintainceCertificateTxt);
        maintainceCertificateTxt.setBounds(680, 50, 270, 30);
        textPanel.add(airportTxt);
        airportTxt.setBounds(680, 90, 270, 30);
        textPanel.add(availableDateTxt);
        availableDateTxt.setBounds(680, 130, 270, 30);
        textPanel.add(jScrollPane1);
        jScrollPane1.setBounds(-20, -50, 2, 2);

        add(textPanel);
        textPanel.setBounds(50, 450, 960, 280);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteJBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = airlinesTable.getSelectedRow();

        if (selectedRow>=0) {
            Airplanes vs = (Airplanes)airlinesTable.getValueAt(selectedRow, 0);
            airplanesCatalog.deleteAirplanes(vs);
            JOptionPane.showMessageDialog(null,"Airplane has been deleted");
            populateTable();
        }
        else{
            JOptionPane.showMessageDialog(null,"select any row");
        }
    }//GEN-LAST:event_deleteJBtnActionPerformed

    private void viewJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewJBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = airlinesTable.getSelectedRow();
        textPanel.setVisible(true);

        if (selectedRow>=0) {
            Airplanes vs = (Airplanes)airlinesTable.getValueAt(selectedRow, 0);
            serialNoTxt.setText(String.valueOf(vs.getSerialNo()));
            modelNoTxt.setText(String.valueOf(vs.getModelNo()));
            manufacturedByTxt.setText(String.valueOf(vs.getManufacturer()));
            yearTxt.setText(String.valueOf(vs.getYearOfManufacture()));
            numberOfSeatsTxt.setText(String.valueOf(vs.getNumberOfSeats()));
            maintainceCertificateTxt.setText(String.valueOf(vs.getMaintaineneceCertificate()));
            airportTxt.setText(String.valueOf(vs.getAirport()));                        
            SimpleDateFormat date = new SimpleDateFormat("dd-mm-yyyy");
            String departDate = date.format(vs.getDepartureDate());
            availableDateTxt.setText(String.valueOf(departDate));
            
        }
        else{
            JOptionPane.showMessageDialog(null,"select any row");
        }
    }//GEN-LAST:event_viewJBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = airlinesTable.getSelectedRow();
        if (selectedRow>=0) {
            Airplanes vs = (Airplanes)airlinesTable.getValueAt(selectedRow, 0);
            airplanesCatalog.deleteAirplanes(vs);
            
            Date availableDate = null;
            String serialNo = serialNoTxt.getText();
            String modelNo = modelNoTxt.getText();
            String manufacturer = manufacturedByTxt.getText();
            int year = Integer.parseInt(yearTxt.getText());
            int seats = Integer.parseInt(numberOfSeatsTxt.getText());
            String maintainence = maintainceCertificateTxt.getText();
            String airport = airportTxt.getText();
            try {
                availableDate = new SimpleDateFormat("dd-mm-yyyy").parse(availableDateTxt.getText());
            } catch (ParseException ex) {
                Logger.getLogger(CreateJPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Enter the date in proper format");
            return;
            }
            Date catalogueUpdate = new Date();
            Airplanes air = airplanesCatalog.addAirplanes();
            air.setSerialNo(serialNo);
            air.setModelNo(modelNo);
            air.setManufacturer(manufacturer);
            air.setYearOfManufacture(year);
            air.setNumberOfSeats(seats);
            air.setMaintaineneceCertificate(maintainence);
            //air.setAvailabilityDate(availableDate);
            air.setAirport(airport);
            air.setDepartureDate(availableDate);
            air.setCatalogUpdatedDate(catalogueUpdate);
            JOptionPane.showMessageDialog(null, "Airplanes updated Successfully");
            populateTable();
        }
        serialNoTxt.setText("");
        modelNoTxt.setText("");
        manufacturedByTxt.setText("");
        yearTxt.setText("");
        numberOfSeatsTxt.setText("");
        maintainceCertificateTxt.setText("");
        airportTxt.setText("");
        availableDateTxt.setText("");
       
    }//GEN-LAST:event_updateBtnActionPerformed

    private void yearTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearTxtKeyTyped
        // TODO add your handling code here:
        char year= evt.getKeyChar();
        if (!(Character.isDigit(year) || (year==KeyEvent.VK_BACK_SPACE) || (year==KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_yearTxtKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable airlinesTable;
    private javax.swing.JTextField airportTxt;
    private javax.swing.JTextField availableDateTxt;
    private javax.swing.JButton deleteJBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JTextField maintainceCertificateTxt;
    private javax.swing.JTextField manufacturedByTxt;
    private javax.swing.JTextField modelNoTxt;
    private javax.swing.JTextField numberOfSeatsTxt;
    private javax.swing.JTextField serialNoTxt;
    private javax.swing.JPanel textPanel;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton viewJBtn;
    private javax.swing.JTextField yearTxt;
    // End of variables declaration//GEN-END:variables
}
