/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageCustomers;

import Business.Customer;
import Business.Flight;
import Business.TravelAgency;
import UserInterface.ManageAirliners.CreateNewFlightJPanel;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author vikram
 */
public class BookCustomersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookCustomersJPanel
     */
    JPanel cardSequenceJPanel;
    Flight flight;
    TravelAgency travelAgency;
    Customer customer;
    
    BookCustomersJPanel(JPanel cardSequenceJPanel, Flight flight, TravelAgency travelAgency) {
        initComponents();
        this.cardSequenceJPanel = cardSequenceJPanel;
        this.flight = flight;
        this.travelAgency = travelAgency;
        populateAirlineDetails();
        txtAirlinerName.setEnabled(false);
        txtFlightSerialNo.setEnabled(false);
        txtSource.setEnabled(false);
        txtDestination.setEnabled(false);
        txtTime.setEnabled(false);
        txtDateOfDeparture.setEnabled(false); 
        txtSeatPrice.setEnabled(false);
    }
    
    private void populateAirlineDetails(){
        txtAirlinerName.setText(flight.getAirlineName());
        txtFlightSerialNo.setText(flight.getFlightId());
        txtSource.setText(flight.getArrivalLocation());
        txtDestination.setText(flight.getArrivalLocation());
        txtTime.setText(flight.getTimeOfDay());
        SimpleDateFormat date = new SimpleDateFormat("dd/MM/yyyy");
        String departDate = date.format(flight.getDepartureDate()); 
        txtDateOfDeparture.setText(departDate);
        txtSeatPrice.setText(Integer.toString(flight.getPerSeatRate()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAirlinerName = new javax.swing.JTextField();
        txtSource = new javax.swing.JTextField();
        txtDestination = new javax.swing.JTextField();
        txtDateOfDeparture = new javax.swing.JTextField();
        txtTime = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        txtCustomerAge = new javax.swing.JTextField();
        txtCustomerPhone = new javax.swing.JTextField();
        txtCustomerAddress = new javax.swing.JTextField();
        btnBookFlight = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtFlightSerialNo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtSeatPrice = new javax.swing.JTextField();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Book a Flight");
        add(jLabel1);
        jLabel1.setBounds(70, 10, 700, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Source ");
        add(jLabel2);
        jLabel2.setBounds(116, 139, 100, 31);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Airliner");
        add(jLabel3);
        jLabel3.setBounds(116, 66, 100, 31);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Departure Time");
        add(jLabel4);
        jLabel4.setBounds(460, 70, 100, 31);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Destination");
        add(jLabel5);
        jLabel5.setBounds(116, 178, 100, 31);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Date of Departure");
        add(jLabel6);
        jLabel6.setBounds(440, 110, 119, 31);
        add(txtAirlinerName);
        txtAirlinerName.setBounds(234, 68, 184, 31);
        add(txtSource);
        txtSource.setBounds(234, 141, 184, 31);
        add(txtDestination);
        txtDestination.setBounds(234, 178, 184, 31);

        txtDateOfDeparture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateOfDepartureActionPerformed(evt);
            }
        });
        add(txtDateOfDeparture);
        txtDateOfDeparture.setBounds(570, 110, 184, 31);

        txtTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeActionPerformed(evt);
            }
        });
        add(txtTime);
        txtTime.setBounds(570, 70, 184, 31);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Customer Details");
        add(jLabel7);
        jLabel7.setBounds(340, 240, 200, 38);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Age");
        add(jLabel8);
        jLabel8.setBounds(450, 290, 30, 25);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Name");
        add(jLabel9);
        jLabel9.setBounds(140, 290, 86, 25);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Phone Number");
        add(jLabel10);
        jLabel10.setBounds(140, 330, 86, 25);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Address");
        add(jLabel11);
        jLabel11.setBounds(450, 330, 70, 25);
        add(txtCustomerName);
        txtCustomerName.setBounds(230, 290, 159, 25);

        txtCustomerAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCustomerAgeKeyTyped(evt);
            }
        });
        add(txtCustomerAge);
        txtCustomerAge.setBounds(520, 290, 159, 25);

        txtCustomerPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCustomerPhoneKeyTyped(evt);
            }
        });
        add(txtCustomerPhone);
        txtCustomerPhone.setBounds(230, 330, 159, 25);
        add(txtCustomerAddress);
        txtCustomerAddress.setBounds(520, 330, 159, 25);

        btnBookFlight.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBookFlight.setText("Book Flight");
        btnBookFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookFlightActionPerformed(evt);
            }
        });
        add(btnBookFlight);
        btnBookFlight.setBounds(360, 430, 113, 36);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Serial Number");
        add(jLabel12);
        jLabel12.setBounds(118, 105, 96, 24);
        add(txtFlightSerialNo);
        txtFlightSerialNo.setBounds(232, 106, 186, 27);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Price of Seat");
        add(jLabel13);
        jLabel13.setBounds(440, 150, 119, 31);

        txtSeatPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeatPriceActionPerformed(evt);
            }
        });
        add(txtSeatPrice);
        txtSeatPrice.setBounds(570, 150, 184, 31);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeActionPerformed

    private void txtDateOfDepartureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateOfDepartureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateOfDepartureActionPerformed

    private void btnBookFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookFlightActionPerformed
        // TODO add your handling code here:
        int seatNo = 1;
        customer = travelAgency.getCustomerDirectory().addCustomer();
        Date availableDate=null;
        customer.setFlightAirlinerName(txtAirlinerName.getText());
        customer.setFlightSerialNo(txtFlightSerialNo.getText());
        customer.setDepartureLocation(txtSource.getText());
        customer.setArrivalLocation(txtDestination.getText());
        customer.setTimeOfDay(txtTime.getText());
        try {
            availableDate = new SimpleDateFormat("dd/MM/yyyy").parse(txtDateOfDeparture.getText());
        }
        catch (ParseException ex) {
            Logger.getLogger(CreateNewFlightJPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Enter the date in proper format");
            return;
        }
        //flight.getSeat().setSeatNumber(seatNo);
//        int count = flight.getSeat().getSeatNumber();
        customer.setDepartureDate(availableDate);
        customer.setCustomerName(txtCustomerName.getText());
        customer.setBookedSeats(seatNo);
        JOptionPane.showMessageDialog(null, "Booking done successfully");
        seatNo++;
    }//GEN-LAST:event_btnBookFlightActionPerformed

    private void txtSeatPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeatPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeatPriceActionPerformed

    private void txtCustomerPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerPhoneKeyTyped
        // TODO add your handling code here:
        char rate= evt.getKeyChar();
        if (!(Character.isDigit(rate) || (rate==KeyEvent.VK_BACK_SPACE) || (rate==KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCustomerPhoneKeyTyped

    private void txtCustomerAgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerAgeKeyTyped
        // TODO add your handling code here:
        char rate= evt.getKeyChar();
        if (!(Character.isDigit(rate) || (rate==KeyEvent.VK_BACK_SPACE) || (rate==KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCustomerAgeKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookFlight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAirlinerName;
    private javax.swing.JTextField txtCustomerAddress;
    private javax.swing.JTextField txtCustomerAge;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtCustomerPhone;
    private javax.swing.JTextField txtDateOfDeparture;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtFlightSerialNo;
    private javax.swing.JTextField txtSeatPrice;
    private javax.swing.JTextField txtSource;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables
}
