/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageUser;

import BusinessPackage.Business;
import BusinessPackage.Person;
import BusinessPackage.PersonDirectory;
import BusinessPackage.UserAccount;
import BusinessPackage.UserAccountDirectory;
import UserInterface.ManagePerson.NewPersonJPanel;
import java.awt.CardLayout;
import javax.swing.DefaultCellEditor;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vikram
 */
public class ManageUserAccountDirectory extends javax.swing.JPanel {

    /**
     * Creates new form ManageUserAccountDirectory
     */
    JPanel userProcessContainer;
    Business business;
    Person person;
    public ManageUserAccountDirectory(JPanel userProcessContainer,Business business,Person person) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.person=person;
        populateTable();
    }

    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblUserAccounts.getModel();
        dtm.setRowCount(0);
        JPasswordField pwf = new JPasswordField();
        DefaultCellEditor editor = new DefaultCellEditor(pwf);
        tblUserAccounts.getColumnModel().getColumn(1).setCellEditor(editor);
        for(Person person: business.getPersonDirectory().getPersonList()) {
            Object row[] = new Object[4];
            
            if (person.getUserAccount()==null) {
                continue;
            }
            else{
                row[0] = person;
                row[1] = person.getUserAccount().getUserName();
                row[2] = person.getUserAccount().getPassword();
                row[3] = person.getUserAccount().getRole();
            }
            dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUserAccounts = new javax.swing.JTable();
        btnFindUserAccount = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdateUserAccount = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnNewUserAccount1 = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage User Account Directory");
        add(jLabel1);
        jLabel1.setBounds(187, 11, 481, 50);

        tblUserAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Person", "User Name", "Password", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUserAccounts);
        if (tblUserAccounts.getColumnModel().getColumnCount() > 0) {
            tblUserAccounts.getColumnModel().getColumn(0).setMinWidth(0);
            tblUserAccounts.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblUserAccounts.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(18, 165, 548, 220);

        btnFindUserAccount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFindUserAccount.setText("Find User Account >>");
        btnFindUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindUserAccountActionPerformed(evt);
            }
        });
        add(btnFindUserAccount);
        btnFindUserAccount.setBounds(567, 118, 215, 40);

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete);
        btnDelete.setBounds(570, 480, 215, 30);

        btnUpdateUserAccount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdateUserAccount.setText("Update User Account >>");
        btnUpdateUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUserAccountActionPerformed(evt);
            }
        });
        add(btnUpdateUserAccount);
        btnUpdateUserAccount.setBounds(570, 440, 215, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("User Accounts");
        add(jLabel2);
        jLabel2.setBounds(27, 128, 150, 30);

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(20, 420, 150, 40);

        btnNewUserAccount1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNewUserAccount1.setText("New User Account >>");
        btnNewUserAccount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewUserAccount1ActionPerformed(evt);
            }
        });
        add(btnNewUserAccount1);
        btnNewUserAccount1.setBounds(567, 398, 215, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindUserAccountActionPerformed
        // TODO add your handling code here:
        SearchUserJPanel panel = new SearchUserJPanel(userProcessContainer,business);
        userProcessContainer.add("SearchUserJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnFindUserAccountActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblUserAccounts.getSelectedRow();
        if (selectedRow>=0) {
            Person person = (Person) tblUserAccounts.getValueAt(selectedRow,0);
            business.getPersonDirectory().deletePerson(person);
            business.getUserAccountDirectory().deleteUser(person.getUserAccount());
            JOptionPane.showMessageDialog(null,"User has been deleted");
            populateTable();
        }
        else{
            JOptionPane.showMessageDialog(null,"select any row");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserAccountActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblUserAccounts.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        Person person = (Person) tblUserAccounts.getValueAt(selectedRow,0);
        UpdateUserJPanel panel = new UpdateUserJPanel(userProcessContainer,business,person);
        userProcessContainer.add("UpdateUserJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnUpdateUserAccountActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNewUserAccount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewUserAccount1ActionPerformed
        // TODO add your handling code here:
        NewUserAccountJPanel panel = new NewUserAccountJPanel(userProcessContainer,business);
        userProcessContainer.add("NewUserAccountJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnNewUserAccount1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFindUserAccount;
    private javax.swing.JButton btnNewUserAccount1;
    private javax.swing.JButton btnUpdateUserAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUserAccounts;
    // End of variables declaration//GEN-END:variables
}
