/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageUser;

import UserInterface.ManagePerson.ManagePersonDirectoryJPanel;
import BusinessPackage.Business;
import BusinessPackage.Person;
import BusinessPackage.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author vikram
 */
public class SystemAdminWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkArea
     */
    JPanel userProcessContainer;
    Business business;
    Person person;
    public SystemAdminWorkArea(JPanel userProcessContainer,Business business,Person person) {
        initComponents();
        this.userProcessContainer =userProcessContainer;
        this.business = business;
        
        txtUserName.setText(person.getUserAccount().getUserName());
        txtPerson.setText(person.toString());
        txtRole.setText(person.getUserAccount().getRole());
        txtUserName.setEnabled(false);
        txtPerson.setEnabled(false);
        txtRole.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPerson = new javax.swing.JTextField();
        txtRole = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        btnManageUserAccount = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Role");
        add(jLabel1);
        jLabel1.setBounds(40, 160, 80, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("User Name");
        add(jLabel2);
        jLabel2.setBounds(40, 80, 80, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Person Name");
        add(jLabel5);
        jLabel5.setBounds(30, 120, 90, 30);
        add(txtPerson);
        txtPerson.setBounds(120, 120, 210, 30);
        add(txtRole);
        txtRole.setBounds(120, 160, 210, 30);

        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        add(txtUserName);
        txtUserName.setBounds(120, 80, 210, 30);

        btnManageUserAccount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnManageUserAccount.setText("Manage User Accounts >>");
        btnManageUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUserAccountActionPerformed(evt);
            }
        });
        add(btnManageUserAccount);
        btnManageUserAccount.setBounds(390, 260, 300, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUserAccountActionPerformed
        // TODO add your handling code here:
        ManageUserAccountDirectory panel = new ManageUserAccountDirectory(userProcessContainer,business,person);
        userProcessContainer.add("ManageUserAccountDirectory", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageUserAccountActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageUserAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtPerson;
    private javax.swing.JTextField txtRole;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
