/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Person;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
/**
 *
 * @author vikram
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    Person person = new Person();
    public ViewJPanel(Person person) {
        initComponents();
        DisplayPerson(person);
    }

    private void DisplayPerson(Person person){
        
        //Created User details to be displayed.
        firstNamePersonTxt.setText(person.getFirstName());
        lastNamePersonTxt.setText(person.getLastName());
        dobPersonTxt.setText(person.getDateOfBirth());
        emailPersonTxt.setText(person.getEmailId());
        phonePersonTxt.setText(person.getPhoneNumber());
        photoLabel.setIcon(person.getIcon());
        
        //Created User's Address to be displayed.
        streetLine1Txt.setText(person.address.getStreetLine1());
        streetLine2Txt.setText(person.address.getStreetLine2());
        cityTxt.setText(person.address.getCity());
        stateTxt.setText(person.address.getState());
        pinCodeTxt.setText(person.address.getPincode());
        countryTxt.setText(person.address.getCountry());
        
        //Created User's Financial Accounts Details to be displayed.
        checkingsAccNoTxt.setText(person.financialAccounts.getCheckingsAccNumber());
        savingsAccNoTxt.setText(person.financialAccounts.getSavingsAccNumber());
        checkingsAccCreationDtTxt.setText(person.financialAccounts.getCheckingsAccCreationDate());
        savingsAccCreationDateTxt.setText(person.financialAccounts.getSavingsAccCreationDate());
        checkingsAccStatusTxt.setText(person.financialAccounts.getCheckingsAccStatus());
        savingsAccStatusTxt.setText(person.financialAccounts.getSavingsAccStatus());
        
        //Created User's Credit Card Details to be displayed.
        cardNumberTxt.setText(person.creditCard.getCardNumber());
        cardIssueDate.setText(person.creditCard.getIssueDate());
        cardExpiryDateTxt.setText(person.creditCard.getExpiryDate());
        cardTypeTxt.setText(person.creditCard.getTypeOfCard());
        cardIssuedByTxt.setText(person.creditCard.getIssuedByBank());
        
        //Created User's Driving Liscence Details to be displayed.
        liscenceIdTxt.setText(person.liscenceData.getLiscenceId());
        liscenceIssueDateTxt.setText(person.liscenceData.getIssueDate());
        liscenceExpiryDateTxt.setText(person.liscenceData.getExpiryDate());
        liscenceIssuedByTxt.setText(person.liscenceData.getStateIssued());
        liscenceRestrictionTxt.setText(person.liscenceData.getStateIssued());
        
        //Created User's Spouse Details to be displayed.
        spouseFirstNameTxt.setText(person.spouse.getFirstName());
        spouseLastNameTxt.setText(person.spouse.getLastName());
        spouseDobTxt.setText(person.spouse.getDob());
        spouseEmailIdTxt.setText(person.spouse.getEmailId());
        spousePhoneNoTxt.setText(person.spouse.getPhoneNo());

        //To display the User's Profile Picture.
        photoLabel.setIcon(person.getIcon());
        
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        photoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lastNamePersonTxt = new javax.swing.JTextField();
        dobPersonTxt = new javax.swing.JTextField();
        emailPersonTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        firstNamePersonTxt = new javax.swing.JTextField();
        streetLine2Txt = new javax.swing.JTextField();
        cityTxt = new javax.swing.JTextField();
        stateTxt = new javax.swing.JTextField();
        pinCodeTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        countryTxt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        cardNumberTxt = new javax.swing.JTextField();
        cardIssueDate = new javax.swing.JTextField();
        cardExpiryDateTxt = new javax.swing.JTextField();
        cardTypeTxt = new javax.swing.JTextField();
        cardIssuedByTxt = new javax.swing.JTextField();
        streetLine1Txt = new javax.swing.JTextField();
        phonePersonTxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        liscenceIdTxt = new javax.swing.JTextField();
        liscenceIssueDateTxt = new javax.swing.JTextField();
        liscenceExpiryDateTxt = new javax.swing.JTextField();
        liscenceIssuedByTxt = new javax.swing.JTextField();
        liscenceRestrictionTxt = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        savingsAccNoTxt = new javax.swing.JTextField();
        spouseFirstNameTxt = new javax.swing.JTextField();
        spouseLastNameTxt = new javax.swing.JTextField();
        spouseDobTxt = new javax.swing.JTextField();
        checkingsAccCreationDtTxt = new javax.swing.JTextField();
        savingsAccCreationDateTxt = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        checkingsAccStatusTxt = new javax.swing.JTextField();
        savingsAccStatusTxt = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        spousePhoneNoTxt = new javax.swing.JTextField();
        spouseEmailIdTxt = new javax.swing.JTextField();
        checkingsAccNoTxt = new javax.swing.JTextField();

        setLayout(null);

        photoLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(photoLabel);
        photoLabel.setBounds(1030, 50, 140, 140);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("View User Details");
        add(jLabel1);
        jLabel1.setBounds(470, 10, 220, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Personal Details");
        add(jLabel2);
        jLabel2.setBounds(60, 70, 160, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("First Name");
        add(jLabel3);
        jLabel3.setBounds(60, 130, 80, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Last Name");
        add(jLabel4);
        jLabel4.setBounds(60, 160, 80, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("DOB");
        add(jLabel5);
        jLabel5.setBounds(60, 200, 70, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Email ID");
        add(jLabel6);
        jLabel6.setBounds(60, 240, 70, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Phone Number");
        add(jLabel7);
        jLabel7.setBounds(40, 280, 100, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Address");
        add(jLabel8);
        jLabel8.setBounds(410, 70, 71, 30);

        lastNamePersonTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNamePersonTxtActionPerformed(evt);
            }
        });
        add(lastNamePersonTxt);
        lastNamePersonTxt.setBounds(140, 160, 130, 30);

        dobPersonTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobPersonTxtActionPerformed(evt);
            }
        });
        add(dobPersonTxt);
        dobPersonTxt.setBounds(140, 200, 130, 30);
        add(emailPersonTxt);
        emailPersonTxt.setBounds(140, 240, 130, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Street Line1");
        add(jLabel9);
        jLabel9.setBounds(340, 120, 100, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Street Line2");
        add(jLabel10);
        jLabel10.setBounds(340, 160, 100, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("City");
        add(jLabel11);
        jLabel11.setBounds(340, 210, 60, 17);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("State");
        add(jLabel12);
        jLabel12.setBounds(340, 280, 80, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Pin Code");
        add(jLabel13);
        jLabel13.setBounds(340, 240, 80, 30);
        add(firstNamePersonTxt);
        firstNamePersonTxt.setBounds(140, 120, 130, 30);

        streetLine2Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetLine2TxtActionPerformed(evt);
            }
        });
        add(streetLine2Txt);
        streetLine2Txt.setBounds(440, 160, 130, 30);

        cityTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityTxtActionPerformed(evt);
            }
        });
        add(cityTxt);
        cityTxt.setBounds(440, 200, 130, 30);

        stateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateTxtActionPerformed(evt);
            }
        });
        add(stateTxt);
        stateTxt.setBounds(440, 280, 130, 30);

        pinCodeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinCodeTxtActionPerformed(evt);
            }
        });
        add(pinCodeTxt);
        pinCodeTxt.setBounds(440, 240, 130, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Country");
        add(jLabel14);
        jLabel14.setBounds(340, 320, 80, 30);

        countryTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryTxtActionPerformed(evt);
            }
        });
        add(countryTxt);
        countryTxt.setBounds(440, 320, 130, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Issue Date");
        add(jLabel17);
        jLabel17.setBounds(730, 170, 70, 20);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Expiry Date");
        add(jLabel18);
        jLabel18.setBounds(730, 210, 80, 20);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Issued By");
        add(jLabel20);
        jLabel20.setBounds(730, 290, 70, 20);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Credit Card Details");
        add(jLabel21);
        jLabel21.setBounds(730, 70, 168, 22);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Card Number");
        add(jLabel24);
        jLabel24.setBounds(730, 130, 90, 20);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Card Type");
        add(jLabel27);
        jLabel27.setBounds(730, 250, 70, 20);

        cardNumberTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNumberTxtActionPerformed(evt);
            }
        });
        add(cardNumberTxt);
        cardNumberTxt.setBounds(830, 130, 130, 30);

        cardIssueDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardIssueDateActionPerformed(evt);
            }
        });
        add(cardIssueDate);
        cardIssueDate.setBounds(830, 170, 130, 30);

        cardExpiryDateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardExpiryDateTxtActionPerformed(evt);
            }
        });
        add(cardExpiryDateTxt);
        cardExpiryDateTxt.setBounds(830, 210, 130, 30);

        cardTypeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardTypeTxtActionPerformed(evt);
            }
        });
        add(cardTypeTxt);
        cardTypeTxt.setBounds(830, 250, 130, 30);

        cardIssuedByTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardIssuedByTxtActionPerformed(evt);
            }
        });
        add(cardIssuedByTxt);
        cardIssuedByTxt.setBounds(830, 290, 130, 30);

        streetLine1Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetLine1TxtActionPerformed(evt);
            }
        });
        add(streetLine1Txt);
        streetLine1Txt.setBounds(440, 120, 130, 30);

        phonePersonTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonePersonTxtActionPerformed(evt);
            }
        });
        add(phonePersonTxt);
        phonePersonTxt.setBounds(140, 280, 130, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Liscence Details");
        add(jLabel15);
        jLabel15.setBounds(790, 390, 145, 22);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Liscence ID");
        add(jLabel16);
        jLabel16.setBounds(780, 460, 70, 17);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Restriction");
        add(jLabel19);
        jLabel19.setBounds(790, 620, 64, 20);

        liscenceIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liscenceIdTxtActionPerformed(evt);
            }
        });
        add(liscenceIdTxt);
        liscenceIdTxt.setBounds(890, 460, 130, 30);

        liscenceIssueDateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liscenceIssueDateTxtActionPerformed(evt);
            }
        });
        add(liscenceIssueDateTxt);
        liscenceIssueDateTxt.setBounds(890, 500, 130, 30);

        liscenceExpiryDateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liscenceExpiryDateTxtActionPerformed(evt);
            }
        });
        add(liscenceExpiryDateTxt);
        liscenceExpiryDateTxt.setBounds(890, 540, 130, 30);

        liscenceIssuedByTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liscenceIssuedByTxtActionPerformed(evt);
            }
        });
        add(liscenceIssuedByTxt);
        liscenceIssuedByTxt.setBounds(890, 580, 130, 30);

        liscenceRestrictionTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liscenceRestrictionTxtActionPerformed(evt);
            }
        });
        add(liscenceRestrictionTxt);
        liscenceRestrictionTxt.setBounds(890, 620, 130, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Financial Accounts");
        add(jLabel22);
        jLabel22.setBounds(40, 390, 169, 22);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Spouse Details");
        add(jLabel23);
        jLabel23.setBounds(440, 390, 132, 22);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Date of Issue");
        add(jLabel25);
        jLabel25.setBounds(790, 510, 90, 17);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Expiry Date");
        add(jLabel26);
        jLabel26.setBounds(790, 550, 72, 17);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Issued by");
        add(jLabel28);
        jLabel28.setBounds(790, 590, 59, 17);

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("Checkings Acc No");
        add(jLabel31);
        jLabel31.setBounds(20, 450, 130, 17);

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("Savings Acc No");
        add(jLabel32);
        jLabel32.setBounds(20, 490, 94, 17);

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("Checkings Acc Creation Date");
        add(jLabel33);
        jLabel33.setBounds(20, 530, 190, 17);

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("Savings Acc Creation Date");
        add(jLabel34);
        jLabel34.setBounds(20, 570, 161, 17);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setText("Checkings Acc Status");
        add(jLabel35);
        jLabel35.setBounds(20, 610, 131, 17);

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setText("First Name");
        add(jLabel36);
        jLabel36.setBounds(410, 450, 80, 17);

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setText("Last Name");
        add(jLabel37);
        jLabel37.setBounds(410, 490, 80, 17);

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel38.setText("DOB");
        add(jLabel38);
        jLabel38.setBounds(410, 530, 28, 17);

        savingsAccNoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingsAccNoTxtActionPerformed(evt);
            }
        });
        add(savingsAccNoTxt);
        savingsAccNoTxt.setBounds(220, 480, 130, 30);

        spouseFirstNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spouseFirstNameTxtActionPerformed(evt);
            }
        });
        add(spouseFirstNameTxt);
        spouseFirstNameTxt.setBounds(510, 450, 130, 30);

        spouseLastNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spouseLastNameTxtActionPerformed(evt);
            }
        });
        add(spouseLastNameTxt);
        spouseLastNameTxt.setBounds(510, 490, 130, 30);

        spouseDobTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spouseDobTxtActionPerformed(evt);
            }
        });
        add(spouseDobTxt);
        spouseDobTxt.setBounds(510, 530, 130, 30);

        checkingsAccCreationDtTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkingsAccCreationDtTxtActionPerformed(evt);
            }
        });
        add(checkingsAccCreationDtTxt);
        checkingsAccCreationDtTxt.setBounds(220, 520, 130, 30);

        savingsAccCreationDateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingsAccCreationDateTxtActionPerformed(evt);
            }
        });
        add(savingsAccCreationDateTxt);
        savingsAccCreationDateTxt.setBounds(220, 560, 130, 30);

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("Savings Acc Status");
        add(jLabel29);
        jLabel29.setBounds(20, 650, 116, 17);

        checkingsAccStatusTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkingsAccStatusTxtActionPerformed(evt);
            }
        });
        add(checkingsAccStatusTxt);
        checkingsAccStatusTxt.setBounds(220, 600, 130, 30);

        savingsAccStatusTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingsAccStatusTxtActionPerformed(evt);
            }
        });
        add(savingsAccStatusTxt);
        savingsAccStatusTxt.setBounds(220, 640, 130, 30);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("Email ID");
        add(jLabel30);
        jLabel30.setBounds(400, 570, 80, 17);

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setText("Phone Number");
        add(jLabel39);
        jLabel39.setBounds(390, 610, 92, 17);

        spousePhoneNoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spousePhoneNoTxtActionPerformed(evt);
            }
        });
        add(spousePhoneNoTxt);
        spousePhoneNoTxt.setBounds(510, 610, 130, 30);

        spouseEmailIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spouseEmailIdTxtActionPerformed(evt);
            }
        });
        add(spouseEmailIdTxt);
        spouseEmailIdTxt.setBounds(510, 570, 130, 30);

        checkingsAccNoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkingsAccNoTxtActionPerformed(evt);
            }
        });
        add(checkingsAccNoTxt);
        checkingsAccNoTxt.setBounds(220, 440, 130, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void lastNamePersonTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNamePersonTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNamePersonTxtActionPerformed

    private void dobPersonTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobPersonTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobPersonTxtActionPerformed

    private void streetLine2TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetLine2TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetLine2TxtActionPerformed

    private void cityTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityTxtActionPerformed

    private void stateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateTxtActionPerformed

    private void pinCodeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinCodeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinCodeTxtActionPerformed

    private void countryTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryTxtActionPerformed

    private void cardNumberTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNumberTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNumberTxtActionPerformed

    private void cardIssueDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardIssueDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardIssueDateActionPerformed

    private void cardExpiryDateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardExpiryDateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardExpiryDateTxtActionPerformed

    private void cardTypeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardTypeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardTypeTxtActionPerformed

    private void cardIssuedByTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardIssuedByTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardIssuedByTxtActionPerformed

    private void streetLine1TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetLine1TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetLine1TxtActionPerformed

    private void phonePersonTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonePersonTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonePersonTxtActionPerformed

    private void liscenceIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liscenceIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_liscenceIdTxtActionPerformed

    private void liscenceIssueDateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liscenceIssueDateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_liscenceIssueDateTxtActionPerformed

    private void liscenceExpiryDateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liscenceExpiryDateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_liscenceExpiryDateTxtActionPerformed

    private void liscenceIssuedByTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liscenceIssuedByTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_liscenceIssuedByTxtActionPerformed

    private void liscenceRestrictionTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liscenceRestrictionTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_liscenceRestrictionTxtActionPerformed

    private void savingsAccNoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingsAccNoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingsAccNoTxtActionPerformed

    private void spouseFirstNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spouseFirstNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseFirstNameTxtActionPerformed

    private void spouseLastNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spouseLastNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseLastNameTxtActionPerformed

    private void spouseDobTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spouseDobTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseDobTxtActionPerformed

    private void checkingsAccCreationDtTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkingsAccCreationDtTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkingsAccCreationDtTxtActionPerformed

    private void savingsAccCreationDateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingsAccCreationDateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingsAccCreationDateTxtActionPerformed

    private void checkingsAccStatusTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkingsAccStatusTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkingsAccStatusTxtActionPerformed

    private void savingsAccStatusTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingsAccStatusTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingsAccStatusTxtActionPerformed

    private void spousePhoneNoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spousePhoneNoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spousePhoneNoTxtActionPerformed

    private void spouseEmailIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spouseEmailIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseEmailIdTxtActionPerformed

    private void checkingsAccNoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkingsAccNoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkingsAccNoTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cardExpiryDateTxt;
    private javax.swing.JTextField cardIssueDate;
    private javax.swing.JTextField cardIssuedByTxt;
    private javax.swing.JTextField cardNumberTxt;
    private javax.swing.JTextField cardTypeTxt;
    private javax.swing.JTextField checkingsAccCreationDtTxt;
    private javax.swing.JTextField checkingsAccNoTxt;
    private javax.swing.JTextField checkingsAccStatusTxt;
    private javax.swing.JTextField cityTxt;
    private javax.swing.JTextField countryTxt;
    private javax.swing.JTextField dobPersonTxt;
    private javax.swing.JTextField emailPersonTxt;
    private javax.swing.JTextField firstNamePersonTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastNamePersonTxt;
    private javax.swing.JTextField liscenceExpiryDateTxt;
    private javax.swing.JTextField liscenceIdTxt;
    private javax.swing.JTextField liscenceIssueDateTxt;
    private javax.swing.JTextField liscenceIssuedByTxt;
    private javax.swing.JTextField liscenceRestrictionTxt;
    private javax.swing.JTextField phonePersonTxt;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JTextField pinCodeTxt;
    private javax.swing.JTextField savingsAccCreationDateTxt;
    private javax.swing.JTextField savingsAccNoTxt;
    private javax.swing.JTextField savingsAccStatusTxt;
    private javax.swing.JTextField spouseDobTxt;
    private javax.swing.JTextField spouseEmailIdTxt;
    private javax.swing.JTextField spouseFirstNameTxt;
    private javax.swing.JTextField spouseLastNameTxt;
    private javax.swing.JTextField spousePhoneNoTxt;
    private javax.swing.JTextField stateTxt;
    private javax.swing.JTextField streetLine1Txt;
    private javax.swing.JTextField streetLine2Txt;
    // End of variables declaration//GEN-END:variables
}
